### ISSUE TITLE
Quick update with current code from YouTube videos.

### ISSUE THREAD

**Issue by jarrodu** [MoonHighway/deno-2-course#3]
I just watched the [Hono video.](https://youtu.be/J8kZ-s-5-ms?si=61K1lMG2jkIzapE4) :-D

Thanks for making it. It was a quick and fun introduction to Hono and CRUD.

Any chance that the code form the recent videos be commit and pushed?

Thanks again. I am looking forward to the rest of the course.

**Comment by eveporcello** [comment]
Thanks @jarrodu! I will push some more changes to the repo in general in the next day or so. In the meantime, I added the files from the Hono video so that you can check them out now! Appreciate the note and thanks for watching the course!
